packages:
  - "apps/*"
  - "libs/*"

autoInstallPeers: true
allowBuilds:
  '@parcel/watcher': true
  '@prisma/client': true
  '@prisma/engines': true
  '@sentry/cli': true
  '@swc/core': true
  esbuild: true
  less: true
  nx: true
  prisma: true
  protobufjs: true
  sharp: true
  unrs-resolver: false
